config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"

  # 利用規約
  get "terms", to: "home#terms"

  # プライバシーポリシー
  get "privacy", to: "home#privacy"

  devise_for :users, skip: [:registration, :session, :password], controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get    "/users/sign_in",  to: "devise/sessions#new",     as: :new_user_session
    get    "/users/sign_up",  to: "home#index",              as: :new_user_registration
    delete "/users/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :articles, only: [:index, :new, :create, :destroy, :update]

  get  "zip/jobs", to: "zip#index",  as: :zip_jobs
  post "zip/jobs", to: "zip#create"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def selected_path(path, t, f)
    request.path == path ? t : f
  end

  def flash_name_to_coler_name(flash_name)
    case flash_name
    when "notice" then
      "blue"
    when "alert" then
      "red"
    end
  end
end

app/views/application/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% coler_name = flash_name_to_coler_name(name) %>
  <%= content_tag :div, class: "text-center bg-#{coler_name}-100 border border-#{coler_name}-400 text-#{coler_name}-700 px-4 py-3 rounded relative" do %>
    <span class="block sm:inline"><%= msg %></span>
  <% end %>
<% end -%>

app/views/application/_header.html.erb
<%= content_for :scripts do %>
  <%= javascript_pack_tag 'application/header' %>
<% end %>

<nav class="bg-gray-800 text-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <a href="/" class="text-4xl">QtoZ</a>
        </div>

        <% if user_signed_in? %>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <!-- クラス名を定義 -->
              <% selected_class = "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <% not_selected_class = "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

              <!-- 記事のインポート -->
              <% link_class_name = selected_path(new_article_path, selected_class, not_selected_class)  %>
              <%= link_to 'インポート', new_article_path, class: link_class_name %>

              <!-- 記事設定 -->
              <% link_class_name = selected_path(articles_path, selected_class, not_selected_class)  %>
              <%= link_to '記事設定', articles_path, class: link_class_name %>

              <!-- ダウンロード -->
              <% link_class_name = selected_path(zip_jobs_path, selected_class, not_selected_class)  %>
              <%= link_to 'ダウンロード', zip_jobs_path, class: link_class_name %>

            </div>
          </div>
        <% end %>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <!-- Profile dropdown -->
          <div class="ml-3 relative">
            <% if user_signed_in?%>
              <div>
                <button 
                  type="button" 
                  class="user-menu-button max-w-xs bg-gray-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                  id="user-menu-button" 
                  aria-expanded="false" 
                  aria-haspopup="true"
                >
                  <span class="sr-only">Open user menu</span>
                  <img class="h-8 w-8 rounded-full" src="<%= current_user.image %>" alt="">
                </button>
              </div>

              <div
                class="user-menu hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" 
                role="menu" 
                aria-orientation="vertical" 
                aria-labelledby="user-menu"
              >
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100' %>
              </div>
            <% else %>
              <div class="ml-3 inline-flex rounded-md shadow">
                <button class="sign-in-modal-button ml-3 px-3 py-2 rounded-md text-sm font-medium text-indigo-600 bg-white hover:bg-indigo-50"> ログイン</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      
      <div class="-mr-2 flex md:hidden">
        <div class="ml-3 relative">
          <% if user_signed_in?%>
            <div>
              <button 
                type="button" 
                class="user-menu-button max-w-xs bg-gray-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                id="user-menu-button" 
                aria-expanded="false" 
                aria-haspopup="true"
              >
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="<%= current_user.image %>" alt="">
              </button>
            </div>

            <div
              class="user-menu hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" 
              role="menu" 
              aria-orientation="vertical" 
              aria-labelledby="user-menu"
            >
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100' %>
            </div>
          <% else %>
            <div class="ml-3 inline-flex rounded-md shadow">
              <button class="sign-in-modal-button ml-3 px-3 py-2 rounded-md text-sm font-medium text-indigo-600 bg-white hover:bg-indigo-50"> ログイン</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="md:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <% if user_signed_in? %>
        <div class="">
          <div class="ml-10 flex justify-center items-baseline space-x-4">
            <!-- クラス名を定義 -->
            <% selected_class = "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% not_selected_class = "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

            <!-- 記事のインポート -->
            <% link_class_name = selected_path(new_article_path, selected_class, not_selected_class)  %>
            <%= link_to 'インポート', new_article_path, class: link_class_name %>

            <!-- 記事設定 -->
            <% link_class_name = selected_path(articles_path, selected_class, not_selected_class)  %>
            <%= link_to '記事設定', articles_path, class: link_class_name %>

            <!-- ダウンロード -->
            <% link_class_name = selected_path(zip_jobs_path, selected_class, not_selected_class)  %>
            <%= link_to 'ダウンロード', zip_jobs_path, class: link_class_name %>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

<!--Modal-->
<div class="sign-in-modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
  <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
  
  <div class="modal-container bg-white text-gray-800 w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
    
    <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
      <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
      </svg>
    </div>

    <!-- Add margin if you want to see some of the overlay behind the modal-->
    <div class="modal-content py-4 text-left px-6">
      <!--Title-->
      <div class="flex justify-between text-center items-center pb-3">
        <p class="text-2xl font-bold text-center">QtoZ</p>
        <div class="modal-close cursor-pointer z-50">
          <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
          </svg>
        </div>
      </div>

      <!--Body-->
      <p>Qiitaアカウントがあればログインできます。</p>
      <p>新規登録は不要です！</p>

      <!--Footer-->
      <div class="flex justify-center pt-2 mt-5">
        <%= link_to 'Login with Qiita', user_qiita_omniauth_authorize_path, method: :post, class: "px-4 bg-transparent p-3 rounded-lg text-white bg-qiita-green hover:bg-gray-100 hover:text-indigo-400 mr-2" %>
      </div>

      <p class="mt-5 text-sm ">
        <%= link_to '利用規約', terms_path, class: "border-b border-gray-800" %>、
        <%= link_to 'プライバシーポリシー', terms_path, class: "border-b border-gray-800" %>
        に同意したうえでログインしてください。
      </p>
      
    </div>
  </div>
</div>
</div>

<header class="bg-white shadow">
  <% if content_for?(:content_title) %>
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold text-gray-900">
        <%= yield(:content_title) %> 
      </h1>
    </div>
  <% end %>
</header>